# Generated by Django 4.2.2 on 2023-06-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_user_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("recipients", models.TextField()),
                ("sent_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["id"],
                "verbose_name": "Country",
                "verbose_name_plural": "countries",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["id"],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.AlterModelOptions(
            name="documenttype",
            options={
                "ordering": ["id"],
                "verbose_name": "DocumentType",
                "verbose_name_plural": "DocumentsTypes",
            },
        ),
    ]
